### ISSUE TITLE
Jetson TX

### ISSUE THREAD

**Issue by frankvp11** [jetson-nano-wheels/python3.6-pycuda-2021.1#2]
Do those pip wheels work on a Jetson TX2 aswell?

**Comment by austinjp** [comment]
Hi there. No idea unfortunately, I only have a Nano, and I haven't used it for a long time now!

About the supplied wheels: https://github.com/jetson-nano-wheels/jetson-nano-wheels

If you're feeling adventurous you can just try building them yourself, of course. Check out the [init.sh](https://github.com/jetson-nano-wheels/python3.7-numpy-1.20.3/blob/main/init.sh) and [build.sh](https://github.com/jetson-nano-wheels/python3.7-numpy-1.20.3/blob/main/build.sh) scripts in https://github.com/jetson-nano-wheels/python3.7-numpy-1.20.3 to see the sort of hoops I found myself jumping through.

And of course feel free to fork :)

**Comment by frankvp11** [comment]
Alright thanks :D- btw  I like the wontfix tag
